### ISSUE TITLE
Aard 2 crashes on any entry selection

### ISSUE THREAD

**Issue by cosmopol** [itkach/aard2-android#101] opened 2019-10-22 22:06 UTC
My Aard 2 crashes when I select any entry on "dewiki-20190705.slob" (German Wikipedia downloaded from your link list) As far as I know, it has worked before. I have no option to check the dictionary. I believe it was possible with Aard 1(?). I have already moved the app to internal memory and wiped its data via settings menu.

"Aard 2 has stopped"

Samsung S4 mini, Android 7.1.2 (AOKP), XprivacyLua (deactivated for Aard 2)

Dev, what can I do to assist you in debugging the app?

**Comment by cosmopol** [comment] 2019-10-22 22:10
check - V0.43

**Comment by itkach** [comment] 2019-10-24 13:16
>  I have no option to check the dictionary.

Use [one of the numerous Andoid apps](https://play.google.com/store/search?q=checksum%20sha1&c=apps&hl=en_US) to calculate dictionary file sha1 on the device and compare it with one specified on the download page

**Comment by MHBraun** [comment] 2019-10-27 15:34
If you do not have the dewiki-20190705.slob.sha1 file you are not able to compare. This file does list the sha1 value for the files.
The dewiki-20190705.slob is old and replaced by the latest dewiki-20191005.slob with the corresponding dewiki-20191005.slob.sha1

**Comment by cosmopol** [comment] 2019-10-29 18:52
dewiki-20190705.slob
sha1:2b3e1c7a3d07334be14bf81c608ef3cf1dfbc25f
md5:134a8edf95a6f59f5bbd45b0c511942f

I have no way to check the original hash value against my values. Anyhow maybe it is a bug of some kind, because I have had similar issues quite often exclusively with Aard 2. If so, I would like to help to track down the bug.

**Comment by cosmopol** [comment] 2019-10-29 18:58
...somewhere here inbetween maybe, there is no searchable commit (any more?)
update of dictionaries
@MHBraun MHBraun committed on 4 Aug
e49385c

update plwiki
@sepanko sepanko committed on 18 Jul
5a24cd0

**Comment by cosmopol** [comment] 2019-10-29 18:58
(https://github.com/itkach/slob/wiki/Dictionaries/_history)

**Comment by itkach** [comment] 2019-10-29 19:34
>  have no way to check the original hash value against my values. 

can you download latest dictionary file? any reason you must stick to one you have?

> because I have had similar issues quite often exclusively with Aard 2. 

no sure what does that mean... similar how? exclusively in what way?

> Anyhow maybe it is a bug of some kind...  If so, I would like to help to track down the bug.

Did you install Aard 2 from Play Store? Does your system prompt to submit report when it crashes? That would be one way. I don't see any recent crash reports in Play Store's developer console though.

Another way would be to observe log output with [`adb logcat`](https://developer.android.com/studio/command-line/logcat)

XprivacyLua is interesting. Not sure how exactly it works and what is its impact on Aard 2, if any, but would be interesting to see if it still crashes with XprivacyLua uninstalled/deactivated

**Comment by MHBraun** [comment] 2019-10-30 00:46
Is there a specific reason you do not want to update to an acutal version with sha1 file?
The sha1 file of the dictionary you are using is deleted on the mirror.
-- 
Sent from my Android phone with WEB.DE Mail. Please excuse my brevity.On 10/29/19, 13:52 cosmopol <notifications@github.com> wrote:
dewiki-20190705.slob
sha1:2b3e1c7a3d07334be14bf81c608ef3cf1dfbc25f
md5:134a8edf95a6f59f5bbd45b0c511942f
I have no way to check the original hash value against my values. Anyhow maybe it is a bug of some kind, because I have had similar issues quite often exclusively with Aard 2. If so, I would like to help to track down the bug.

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/itkach/aard2-android/issues/101?email_source=notifications\u0026email_token=AAYE2S54D3ROYBCIDXOBJOTQRCA5DA5CNFSM4JDYQ272YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOECRVT2Y#issuecomment-547576299",
"url": "https://github.com/itkach/aard2-android/issues/101?email_source=notifications\u0026email_token=AAYE2S54D3ROYBCIDXOBJOTQRCA5DA5CNFSM4JDYQ272YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOECRVT2Y#issuecomment-547576299",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by cosmopol** [comment] 2019-10-31 17:06
> Did you install Aard 2 from Play Store?

No. Vanilla.

> Is there a specific reason you do not want to update to an acutal version with sha1 file? The sha1 file of the dictionary you are using is deleted on the mirror.

Yes, I suspect a bug of some kind. If I remember correctly, it always works at first and then this.

> XprivacyLua is interesting. Not sure how exactly it works and what is its impact on Aard 2, if any, but would be interesting to see if it still crashes with XprivacyLua uninstalled/deactivated

It works with xposed framework and hooks all api calls to spoof them. Deactivating it is no option. As soon as the average Joe does that instand location tracking usually follows. Who on earth would want that?


> Another way would be to observe log output with [`adb logcat`](https://developer.android.com/studio/command-line/logcat)

OK, I will try it with a current slob file afterwards, I really wanted to track it down this time. I will look into it.

BTW: Is is possible that Aard 2 writes to slobs occasionally? How about taking away write access if the case may be.

PS: I really hope I really found a bug and not that my SD card is simply broken etc.

**Comment by cosmopol** [comment] 2019-11-02 12:11
Line 5416: 11-02 13:04:26.537  3028  3028 E AndroidRuntime: android.view.InflateException: Binary XML file line #6: Binary XML file line #6: Error inflating class itkach.aard2.ArticleWebView
	Line 5417: 11-02 13:04:26.537  3028  3028 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #6: Error inflating class itkach.aard2.ArticleWebView

**Comment by cosmopol** [comment] 2019-11-02 12:15
BTW: I AM ON BROMITE!

**Comment by cosmopol** [comment] 2019-11-02 12:19
Line 5: 11-02 13:04:26.537  3028  3028 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #6: Error inflating class itkach.aard2.ArticleWebView
	Line 6: 11-02 13:04:26.537  3028  3028 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
	Line 62: 11-02 13:04:26.539  3028  3028 E AndroidRuntime: Caused by: android.util.AndroidRuntimeException: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
	Line 78: 11-02 13:04:26.539  3028  3028 E AndroidRuntime: Caused by: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed

**Comment by cosmopol** [comment] 2019-11-02 12:25
referring to WebView, my chromium derivate browser with spoofing works, so the WebView hack in itself is not the problem.

**Comment by cosmopol** [comment] 2019-11-02 12:31
I am pretty sure it is a minor feature or namespace issue of some kind - would have to study the source code.

**Comment by cosmopol** [comment] 2019-11-02 12:34
...for those who might not know: WebView is the browser framework Google uses to spy on everyone though metadata and stochastics. It is not spyware itself, but the effects are similar. Google once more tries to be evil while pretending to be not. :-)

**Comment by cosmopol** [comment] 2019-11-03 18:15
Mr. Tkach, I would like to track down the error on my own to learn more about Java. I have some .NET experience already. I would like you to guide me a little bit please. It pays off in the long run I suppose. Firstly, I fail to ad hoc grasp the concept behind the 'R' object in ArticleFragment.java:153.

**Comment by itkach** [comment] 2019-11-12 23:15
Sounds like you identified the root cause of the issue, which is not the app itself, so closing the issue.

**Closed by itkach** 2019-11-12 23:15 UTC

**Comment by cosmopol** [comment] 2019-11-14 10:41
> 
> 
> Sounds like you identified the root cause of the issue, which is not the app itself, so closing the issue.

In case you are the original author of Aard 2 and know all its source code by heart, I would kindly ask you to assist me in debugging. Right now my Eclipse IDE cannot resolve the 'R' object in the Aard2 source code.

**Comment by itkach** [comment] 2019-11-14 14:57
> Right now my Eclipse IDE

Google stopped supporting Android development with Eclipse a while ago, you have to use Android Studio (https://developer.android.com/studio/)

> assist me in debugging

I can't. README provides basic instructions on setting up dev environment with Android Studio and there's a lot of documentation out there on working with it - once you get through the setup and have a working dev environment you'll have everything you need to do it yourself.

Not sure what are you trying to achieve though. Rewrite Aard 2 to not depend on WebView? What would it use instead?

**Comment by cosmopol** [comment] 2019-11-14 15:23
> Google stopped supporting Android development with Eclipse a while ago, you have to use Android Studio

stupid me! thanks!

> Not sure what are you trying to achieve though. Rewrite Aard 2 to not depend on WebView? What would it use instead?

As I already mentioned I suspect a minor compatibilty issue. I do not intend to exchange WebView functionality. Bromite is trending strong. I suspect the user count in the millions already. Xposed Framework already has a user count in the tens of millions. Those standard power user utilities just cannot be ignored. I believe that using Android w/o those is impossible.

Do I too need some Gradle training etc. to understand your code?

**Comment by cosmopol** [comment] 2020-02-24 19:52
Damn! Now I have some time again to tackle the issue and I don't have the affected device anymore! Maybe I could use an emulator? Anyone familiar with using emulators for bug hunting?
