### ISSUE TITLE
Crashes on Android14 (crdroid 10)

### ISSUE THREAD

**Issue by darkgeek** [itkach/aard2-android#176] opened 2024-01-12 18:41 UTC
This app crashed everytime upon launching:

```
java.util.MissingResourceException: Could not find the bundle com/ibm/icu/impl/data/icudt68b/keyTypeData.res
stacktrace: java.lang.ExceptionInInitializerError
	at com.ibm.icu.util.ULocale.toLegacyKey(ULocale.java:3609)
	at com.ibm.icu.util.ULocale$JDKLocaleHelper.toULocale(ULocale.java:4324)
	at com.ibm.icu.util.ULocale$2.createInstance(ULocale.java:364)
	at com.ibm.icu.util.ULocale$2.createInstance(ULocale.java:361)
	at com.ibm.icu.impl.SoftCache.getInstance(SoftCache.java:69)
	at com.ibm.icu.util.ULocale.forLocale(ULocale.java:429)
	at com.ibm.icu.util.ULocale.<clinit>(ULocale.java:558)
	at com.ibm.icu.text.Collator.getInstance(Collator.java:858)
	at itkach.slob.Slob$KeyComparator.<init>(Slob.java:1031)
	at itkach.slob.Slob$KeyComparator.<init>(Slob.java:1026)
	at itkach.slob.Slob$Strength.<init>(Slob.java:228)
	at itkach.slob.Slob$Strength.<init>(Slob.java:221)
	at itkach.slob.Slob$Strength.<clinit>(Slob.java:205)
	at itkach.aard2.BlobDescriptorList.<init>(BlobDescriptorList.java:64)
	at itkach.aard2.BlobDescriptorList.<init>(BlobDescriptorList.java:53)
	at itkach.aard2.Application.onCreate(Application.java:135)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1322)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7058)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2261)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8244)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
Caused by: java.util.MissingResourceException: Could not find the bundle com/ibm/icu/impl/data/icudt68b/keyTypeData.res
	at com.ibm.icu.impl.ICUResourceBundle.getBundleInstance(ICUResourceBundle.java:1205)
	at com.ibm.icu.impl.locale.KeyTypeData.initFromResourceBundle(KeyTypeData.java:222)
	at com.ibm.icu.impl.locale.KeyTypeData.<clinit>(KeyTypeData.java:671)
	... 27 more
```
My phone is Oneplus 11, where crdroid 10 runs there.

**Comment by itkach** [comment] 2024-01-12 20:19
duplicate of #175

**Closed by itkach** 2024-01-12 20:19 UTC
