### ISSUE TITLE
RuntimeException: Can't create handler inside thread that has not called Looper.prepare()

### ISSUE THREAD

**Issue by max-kammerer** [itkach/aard2-android#31] opened 2015-05-12 18:59 UTC
After calling aard2 via intent

    Intent intent = new Intent("aard2.lookup");
    intent.putExtra(SearchManager.QUERY, "Foo Bar");
    startActivity(intent);

error is occured

05-12 20:01:19.596 E/AndroidRuntime(22326): FATAL EXCEPTION: AsyncTask #1
05-12 20:01:19.596 E/AndroidRuntime(22326): Process: itkach.aard2, PID: 22326
05-12 20:01:19.596 E/AndroidRuntime(22326): java.lang.RuntimeException: An error occured while executing doInBackground()
05-12 20:01:19.596 E/AndroidRuntime(22326): at android.os.AsyncTask$3.done(AsyncTask.java:300)
05-12 20:01:19.596 E/AndroidRuntime(22326): at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
05-12 20:01:19.596 E/AndroidRuntime(22326): at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
05-12 20:01:19.596 E/AndroidRuntime(22326): at java.util.concurrent.FutureTask.run(FutureTask.java:242)
05-12 20:01:19.596 E/AndroidRuntime(22326): at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
05-12 20:01:19.596 E/AndroidRuntime(22326): at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
05-12 20:01:19.596 E/AndroidRuntime(22326): at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
05-12 20:01:19.596 E/AndroidRuntime(22326): at java.lang.Thread.run(Thread.java:841)
05-12 20:01:19.596 E/AndroidRuntime(22326): Caused by: java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
05-12 20:01:19.596 E/AndroidRuntime(22326): at android.os.Handler.<init>(Handler.java:200)
05-12 20:01:19.596 E/AndroidRuntime(22326): at android.os.Handler.<init>(Handler.java:114)
05-12 20:01:19.596 E/AndroidRuntime(22326): at android.widget.Toast$TN.<init>(Toast.java:457)
05-12 20:01:19.596 E/AndroidRuntime(22326): at android.widget.Toast.<init>(Toast.java:119)
05-12 20:01:19.596 E/AndroidRuntime(22326): at android.widget.Toast.makeText(Toast.java:286)
05-12 20:01:19.596 E/AndroidRuntime(22326): at android.widget.Toast.makeText(Toast.java:335)
05-12 20:01:19.596 E/AndroidRuntime(22326): at itkach.aard2.ArticleCollectionActivity.createFromIntent(ArticleCollectionActivity.java:240)
05-12 20:01:19.596 E/AndroidRuntime(22326): at itkach.aard2.ArticleCollectionActivity.access$500(ArticleCollectionActivity.java:50)
05-12 20:01:19.596 E/AndroidRuntime(22326): at itkach.aard2.ArticleCollectionActivity$2.doInBackground(ArticleCollectionActivity.java:104)
05-12 20:01:19.596 E/AndroidRuntime(22326): at itkach.aard2.ArticleCollectionActivity$2.doInBackground(ArticleCollectionActivity.java:80)
05-12 20:01:19.596 E/AndroidRuntime(22326): at android.os.AsyncTask$2.call(AsyncTask.java:288)
05-12 20:01:19.596 E/AndroidRuntime(22326): at java.util.concurrent.FutureTask.run(FutureTask.java:237)
05-12 20:01:19.596 E/AndroidRuntime(22326): ... 4 more

**Comment by itkach** [comment] 2015-05-12 19:46
I can't reproduce this, works for me (for example here: https://github.com/itkach/FBReaderJ). 
Perhaps you call `startActivity(intent)` on a background thread?

**Comment by max-kammerer** [comment] 2015-05-13 06:49
This exception obtained from Orion Viewer (https://github.com/tututcd/orion-viewer/) user report on attempt to call aard2 via intent on sgs4 Mini 4.4.2 stock.
I checked that startActivity called from main dispatch thread.

**Comment by itkach** [comment] 2015-05-13 17:16
I see: aard 2 crashes when launched with "Open Dictionary" from Orion's menu because it tries to show a toast message from it's own background thread. It shouldn't crash of course, I'll fix that, but the message would be "Nothing to look up": the `aard2.lookup` intent is for looking things up and no query is being given. I'm not sure why is it interesting/useful to be able to just launch an app from Orion, but that would be a different intent.

**Comment by max-kammerer** [comment] 2015-05-13 17:29
There is also possible to select text in book and translate it with specified dictionary, in such case query is specified. Should i use another intent for this case (same as for aard1?)?

**Comment by itkach** [comment] 2015-05-13 17:36
> select text in book and translate it with specified dictionary

That appears to be working fine

> Should i use another intent for this case

There is just one way to do lookups, at least for now - `aard2.lookup` action

**Comment by itkach** [comment] 2015-05-21 03:37
Fixed in 4ad6972236345e5a4b2277ce654b5acbbb51e3de

**Closed by itkach** 2015-05-21 03:37 UTC
