### ISSUE TITLE
my changing dictionary is shown duplicated in the Dictionaries tab

### ISSUE THREAD

**Issue by ildar** [itkach/aard2-android#152] opened 2023-01-16 10:11 UTC
I'm making and updating my own small dictionary and put it in Android.
That worked well. But I found that the dictionary is shown ~7 times in the Dictionaries tab.

I guess that various versions of a dictionary get different uuids (calculated) hence later versions accepted as a new dict.

**Comment by itkach** [comment] 2023-01-18 16:03
Indeed, every new .slob gets a new uuid. They may have the same label, but are distinct. Dictionaries with the same`uri` tag are understood to provide content in the same collection, same "logical" dictionary (meaning that articles from that dictionary are first in the lookup result when following links). 
I'm not sure if there's an issue or a question here - if you don't need older versions of your dictionary just remove them manually.

**Comment by ildar** [comment] 2023-01-18 18:48
That would be fine to "just remove them manually" but it has bookmarks and
history items bound to those.

**Comment by itkach** [comment] 2023-01-18 19:03
bookmarks and history are not strictly bound to slob by uuid, if your dictionaries have uri tag and it remains the same across versions bookmarks and history should continue to work.

**Comment by ildar** [comment] 2023-01-18 19:31
Unfortunately the app recreates the /app_dictionaries files from slobid-s
it finds in history or bookmarks. No matter how many times I try to delete
them.

**Comment by ildar** [comment] 2023-01-18 20:09
I exactly "forget" them from the app but they come back.
I noted that they come back from the history/bookmarks that refer
particular uuids.

**Comment by itkach** [comment] 2023-01-18 20:25
Well, they don't come back from bookmarks or history, I'm pretty sure. I am unable to reproduce this at all, if I forget a dictionary - it's gone from the app. Dictionary files of course stay where they are unless user deletes them themselves, but there is no way for them to just show up (or come back) in the app

**Comment by itkach** [comment] 2023-01-25 02:16
I will look into this.

**Comment by itkach** [comment] 2023-02-19 15:19
@ildar can you pls try this commit: bd227cbf2c522d82930a0c00f108408a16b8fa71 ?

**Comment by ildar** [comment] 2023-02-19 20:34
I'd love to but can't build it yet:
https://github.com/ildar/aard2-android/actions/runs/4217981805

**Comment by itkach** [comment] 2023-02-19 20:38
Why not build locally?

**Comment by ildar** [comment] 2023-02-19 20:46
I'm not an Android developer. It'll take some time to build it locally. I
usually just push the workflow file and M$ builds it for me.

**Comment by itkach** [comment] 2023-02-19 20:51
It is certainly much easier/quicker to build locally than to figure out
remote built with github actions.

**Comment by itkach** [comment] 2023-02-19 22:40
@ildar here's apk (unzip first) [aard2-android-debug.apk.zip](https://github.com/itkach/aard2-android/files/10778169/aard2-android-debug.apk.zip)

**Comment by ildar** [comment] 2023-02-20 20:33
Thanks.
This one looks like fixing the bug. Tested ~2 minutes, no regressions found

**Comment by itkach** [comment] 2023-03-07 04:29
fixed in bd227cbf2c522d82930a0c00f108408a16b8fa71

**Closed by itkach** 2023-03-07 04:29 UTC
