### ISSUE TITLE
problem with disambiguation pages

### ISSUE THREAD

**Issue by ghostwheel** [itkach/aard2-android#68] opened 2017-05-30 04:16 UTC
I'm often having the following problem:
I look up something (For example "Sphinx"). The page that comes up is the disambiguation page (i.e. "Sphinx (disambiguation)")
Even if I try to click on the simple concept "Sphinx" in that disambiguation page, I still end up on the same disambiguation page.
Thus, I can't get to the main article I'm interested in.
I'm using enwiki-20160806, but I'll try a newer one. And Aard2 v0.35
(I also posted this on the aard discussion forum)

**Comment by itkach** [comment] 2017-05-30 15:28
The issue is that disambiguation page has the same alias (redirect) as the main article. I think this is because Wikipedia at some point changed their convention of how to name disambiguation article vs main article for that title and [mwscrape](https://github.com/itkach/mwscrape) process ended up having the same name both for disambiguation and main article. It probably would go away if we ever do a clean scrape from scratch. I'd be reluctant to try put workarounds for this into the app itself, or even into dictionary converter since this source data issue. Maybe existing mwscrape databases can be fixed with a clean up script, I'll think about it.

In any case, as with any set of articles that have the same title, you can swipe through them and that access the main article that way. It's a bit annoying that following link doesn't take you there, but the content is accessible.

**Closed by itkach** 2017-05-30 15:28 UTC
